version: '3.1'
services:
    mongo:
        image: mongo
        container_name: tec-mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
        networks:
            - teclinux
    mongo-express:
        image: mongo-express
        container_name: tec-mongo-express
        restart: always
        ports:
            - 8081:8081
        networks:
            - teclinux
        depends_on:
            - mongo
    fluentd:
        image: fluentd-custom
        container_name: tec-fluentd
        ports:
            - 24224:24224
            - 24224:24224/udp
        networks:
            - teclinux
        depends_on:
            - mongo
            - elasticsearch
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        container_name: tec-elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - teclinux
    kibana:
        image: docker.elastic.co/kibana/kibana:6.4.0
        container_name: tec-kibana
        ports:
            - 5601:5601
        networks:
            - teclinux
        environment:            
            SERVER_HOST: 0.0.0.0
            ELASTICSEARCH_URL: http://tec-elasticsearch:9200
        depends_on:
            - elasticsearch
    redis:
        image: redis
        container_name: tec-redis
        networks:
            - teclinux
        ports:
            - 6379:6379
    rabbit:
        image: rabbitmq:3.7-management
        container_name: tec-rabbit
        ports:
            - 15671:15671
            - 15672:15672
            - 5671:5671
            - 5672:5672
        networks:
            - teclinux
        volumes:
            - /data_rabbitmq:/var/lib/rabbitmq
    portainer:
        image: portainer/portainer
        container_name: tec-portainer
        ports:
            - 7100:8000
            - 7200:9000
        networks:
            - teclinux
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /data_portainer:/data portainer/portainer
    keycloak:
        image: jboss/keycloak
        container_name: tec-keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        ports:
            - 7500:8443
            - 7600:8080
        networks:
            - teclinux
    postgres-db:
        image: postgres
        container_name: tec-postgres-db
        restart: always
        volumes:
            - /data_postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=masterkey
        networks:
            - teclinux
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        container_name: tec-pgadmin
        environment:
          - PGADMIN_DEFAULT_EMAIL=infra@benner.com.br
          - PGADMIN_DEFAULT_PASSWORD=masterkey
        ports:
          - 7800:80
        networks:
          - teclinux
volumes:
    esdata1:
        driver: local
    mongo:
networks:
    teclinux:
        driver: bridge
