version: '3.5'
services:
    bserver:
        image: bennersistemas/bserver:${VERSION_LABEL}
        container_name: tec-bserver
        isolation: process
        environment:
            - WorkDir=C:\Benner\Install\
            - Driver=${BS_DB_DRIVER}
            - ServerName=${BS_DB_HOST}
            - DatabaseName=${BS_DB_NAME}
            - DbUser=${BS_DB_USER_NAME}
            - DbPass=${BS_DB_USER_PASS}
        volumes:
            - ${BS_WORK_DIR}:C:\Benner\Install\
        ports:
            - 556:556
            - 5331-5350:5331-5350
        networks:
            - tecwindows
    btl:
        image: bennersistemas/btl:${VERSION_LABEL}
        container_name: tec-btl
        environment:
            - Servidor=${BSERVER_HOST}
            - Sistema=${SYSTEM_NAME}
            - Usuario=${SYSTEM_INTERNAL_USER_NAME}
            - LoggingServerAddress=http://${ELASTIC_HOST}:9200
        networks:
            - tecwindows
        depends_on:
            - bserver
    wfl:
        image: bennersistemas/wfl:${VERSION_LABEL}
        container_name: tec-wfl
        environment:
            - superServerHost=${BSERVER_HOST}
            - systemName=${SYSTEM_NAME}
            - user=${SYSTEM_INTERNAL_USER_NAME}
            - password=${SYSTEM_INTERNAL_USER_PASS}
            - notifySenderUser=${SYSTEM_INTERNAL_USER_NAME}
            - loggingServerAddress=http://${ELASTIC_HOST}:9200
        networks:
            - tecwindows
        depends_on:
            - bserver
    wes:
        image: bennersistemas/wes:${VERSION_LABEL}
        container_name: tec-wes
        environment:
            - superserverhost=${BSERVER_HOST}
            - superserversystemname=${SYSTEM_NAME}
            - anonymoususername=${SYSTEM_INTERNAL_USER_NAME}
            - anonymouspassword=${SYSTEM_INTERNAL_USER_PASS}
            - systeminstancename=${SYSTEM_INSTANCE_NAME}
            - loggingserveraddress=http://${ELASTIC_HOST}:9200
            - sessionhost=${REDIS_HOST}
        networks:
            - tecwindows
        volumes:
            - ${WES_C_DATA}:C:\data\
        ports:
            - ${WES_HOST_PORT}:80
        depends_on:
            - bserver
networks:
    tecwindows: